/*
 * Student API
 * Student Demo API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.models;

import java.util.Objects;
import java.util.Arrays;
import com.example.models.StudentAddress;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Student
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-29T06:10:21.661+01:00[Europe/Berlin]")
public class Student {
  @JsonProperty("StudentID")
  private Integer studentID = null;

  @JsonProperty("StudentName")
  private String studentName = null;

  @JsonProperty("Age")
  private Integer age = null;

  @JsonProperty("GroupID")
  private String groupID = null;

  @JsonProperty("Address")
  private StudentAddress address = null;

  public Student studentID(Integer studentID) {
    this.studentID = studentID;
    return this;
  }

   /**
   * Get studentID
   * @return studentID
  **/
  @Schema(example = "3", description = "")
  public Integer getStudentID() {
    return studentID;
  }

  public void setStudentID(Integer studentID) {
    this.studentID = studentID;
  }

  public Student studentName(String studentName) {
    this.studentName = studentName;
    return this;
  }

   /**
   * Get studentName
   * @return studentName
  **/
  @Schema(example = "David", description = "")
  public String getStudentName() {
    return studentName;
  }

  public void setStudentName(String studentName) {
    this.studentName = studentName;
  }

  public Student age(Integer age) {
    this.age = age;
    return this;
  }

   /**
   * Get age
   * @return age
  **/
  @Schema(example = "10", description = "")
  public Integer getAge() {
    return age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }

  public Student groupID(String groupID) {
    this.groupID = groupID;
    return this;
  }

   /**
   * Get groupID
   * @return groupID
  **/
  @Schema(example = "GROUP-3", description = "")
  public String getGroupID() {
    return groupID;
  }

  public void setGroupID(String groupID) {
    this.groupID = groupID;
  }

  public Student address(StudentAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public StudentAddress getAddress() {
    return address;
  }

  public void setAddress(StudentAddress address) {
    this.address = address;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Student student = (Student) o;
    return Objects.equals(this.studentID, student.studentID) &&
        Objects.equals(this.studentName, student.studentName) &&
        Objects.equals(this.age, student.age) &&
        Objects.equals(this.groupID, student.groupID) &&
        Objects.equals(this.address, student.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(studentID, studentName, age, groupID, address);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Student {\n");
    
    sb.append("    studentID: ").append(toIndentedString(studentID)).append("\n");
    sb.append("    studentName: ").append(toIndentedString(studentName)).append("\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    groupID: ").append(toIndentedString(groupID)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
